#
#	Makefile for OpenGCL
#
#	Written by Soo-Hyuk Nam.
#		2004. 1. 15. Thu.
#

VCDEL= *.pch *.mdp *.ncb *.clw *.obj *.aps *.cpl *.awk *.exp *.idb \
	*.opt *.pdb *.map *.res *.ilk *.scc *.bsc *.sbr *.tlb *.plg \
	*.bbs *.lib *.dll *.exe

clean:
	@rm -rf Debug Release out
	@rm -f $(VCDEL)
	@echo clean ok.
